# Generated by Django 2.1.5 on 2019-02-11 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameSolicitado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('situacaoExame', models.CharField(choices=[('A', 'Aguardando Resultado'), ('C', 'Concluido')], max_length=1)),
                ('dtHoraSolic', models.DateTimeField()),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.Medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.Paciente')),
            ],
        ),
        migrations.CreateModel(
            name='TipoExame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('instruções', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='examesolicitado',
            name='tipoExame',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clinica.TipoExame'),
        ),
    ]
