# Generated by Django 2.1.5 on 2019-02-11 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0002_auto_20190211_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='receituario',
            field=models.TextField(blank=True, null=True),
        ),
    ]
