# Generated by Django 2.1.5 on 2019-02-12 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_consulta_receituario'),
    ]

    operations = [
        migrations.AddField(
            model_name='examesolicitado',
            name='consulta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.Consulta'),
        ),
    ]
