# Generated by Django 2.1.5 on 2019-02-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_medicamentos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeGenerico', models.CharField(max_length=100)),
                ('nomeComercial', models.CharField(max_length=100)),
                ('fabricante', models.CharField(max_length=100)),
            ],
        ),
    ]
