# Generated by Django 2.1.5 on 2019-02-19 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_auto_20190218_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='examesolicitado',
            name='resultadoImagem',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='examesolicitado',
            name='resultadoTexto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
